"""create_email_notifications

Revision ID: 94e9f20768cf
Revises: edc7439e47e5
Create Date: 2025-04-11 01:34:20.130255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e9f20768cf'
down_revision: Union[str, None] = 'edc7439e47e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_notifications', sa.Column('recipient_email', sa.String(), nullable=False))
    op.drop_column('email_notifications', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_notifications', sa.Column('email', sa.VARCHAR(), nullable=False))
    op.drop_column('email_notifications', 'recipient_email')
    # ### end Alembic commands ###
